[2025-05-10T01:19:39.847+0000] {processor.py:186} INFO - Started process (PID=67116) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:19:39.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:19:39.849+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:19:39.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:19:39.852+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:19:39.851+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:19:39.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:19:39.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.030 seconds
[2025-05-10T01:20:10.805+0000] {processor.py:186} INFO - Started process (PID=67190) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:20:10.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:20:10.807+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:20:10.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:20:10.810+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:20:10.809+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:20:10.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:20:10.831+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.032 seconds
[2025-05-10T01:20:41.293+0000] {processor.py:186} INFO - Started process (PID=67267) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:20:41.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:20:41.295+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:20:41.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:20:41.297+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:20:41.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:20:41.297+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:20:41.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.022 seconds
[2025-05-10T01:21:11.576+0000] {processor.py:186} INFO - Started process (PID=67337) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:21:11.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:21:11.578+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:21:11.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:21:11.580+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:21:11.579+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:21:11.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:21:11.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.029 seconds
[2025-05-10T01:21:42.272+0000] {processor.py:186} INFO - Started process (PID=67419) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:21:42.290+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:21:42.291+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:21:42.290+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:21:42.293+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:21:42.292+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:21:42.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:21:42.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.043 seconds
[2025-05-10T01:22:12.990+0000] {processor.py:186} INFO - Started process (PID=67502) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:22:12.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:22:12.999+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:22:12.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:22:13.001+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:22:13.000+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:22:13.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:22:13.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.035 seconds
[2025-05-10T01:22:43.559+0000] {processor.py:186} INFO - Started process (PID=67584) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:22:43.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:22:43.561+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:22:43.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:22:43.563+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:22:43.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:22:43.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:22:43.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.026 seconds
[2025-05-10T01:23:14.576+0000] {processor.py:186} INFO - Started process (PID=67666) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:23:14.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:23:14.586+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:23:14.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:23:14.589+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:23:14.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:23:14.589+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:23:14.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.038 seconds
[2025-05-10T01:23:45.251+0000] {processor.py:186} INFO - Started process (PID=67748) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:23:45.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:23:45.254+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:23:45.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:23:45.257+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:23:45.256+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:23:45.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:23:45.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.031 seconds
[2025-05-10T01:24:15.971+0000] {processor.py:186} INFO - Started process (PID=67830) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:24:15.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:24:15.979+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:24:15.979+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:24:15.981+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:24:15.981+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:24:15.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:24:15.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.029 seconds
[2025-05-10T01:24:46.818+0000] {processor.py:186} INFO - Started process (PID=67912) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:24:46.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:24:46.827+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:24:46.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:24:46.830+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:24:46.829+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:24:46.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:24:46.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.036 seconds
[2025-05-10T01:25:17.475+0000] {processor.py:186} INFO - Started process (PID=67994) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:25:17.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:25:17.477+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:25:17.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:25:17.479+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:25:17.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:25:17.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:25:17.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.023 seconds
[2025-05-10T01:25:48.063+0000] {processor.py:186} INFO - Started process (PID=68076) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:25:48.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:25:48.066+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:25:48.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:25:48.068+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:25:48.067+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:25:48.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:25:48.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.025 seconds
[2025-05-10T01:26:18.520+0000] {processor.py:186} INFO - Started process (PID=68158) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:26:18.523+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:26:18.524+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:26:18.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:26:18.526+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:26:18.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:26:18.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:26:18.544+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.031 seconds
[2025-05-10T01:26:49.127+0000] {processor.py:186} INFO - Started process (PID=68240) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:26:49.135+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T01:26:49.136+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:26:49.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:26:49.138+0000] {logging_mixin.py:190} INFO - [2025-05-10T01:26:49.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T01:26:49.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T01:26:49.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.033 seconds
[2025-05-10T02:18:36.343+0000] {processor.py:186} INFO - Started process (PID=68329) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:18:36.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T02:18:36.349+0000] {logging_mixin.py:190} INFO - [2025-05-10T02:18:36.348+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:18:36.358+0000] {logging_mixin.py:190} INFO - [2025-05-10T02:18:36.355+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T02:18:36.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:18:36.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.092 seconds
[2025-05-10T02:19:07.426+0000] {processor.py:186} INFO - Started process (PID=68410) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:19:07.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T02:19:07.435+0000] {logging_mixin.py:190} INFO - [2025-05-10T02:19:07.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:19:07.437+0000] {logging_mixin.py:190} INFO - [2025-05-10T02:19:07.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T02:19:07.437+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:19:07.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.033 seconds
[2025-05-10T02:19:37.554+0000] {processor.py:186} INFO - Started process (PID=68492) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:19:37.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T02:19:37.556+0000] {logging_mixin.py:190} INFO - [2025-05-10T02:19:37.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:19:37.559+0000] {logging_mixin.py:190} INFO - [2025-05-10T02:19:37.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T02:19:37.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:19:37.573+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.023 seconds
[2025-05-10T02:20:08.015+0000] {processor.py:186} INFO - Started process (PID=68574) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:20:08.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T02:20:08.016+0000] {logging_mixin.py:190} INFO - [2025-05-10T02:20:08.016+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:20:08.019+0000] {logging_mixin.py:190} INFO - [2025-05-10T02:20:08.018+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T02:20:08.019+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:20:08.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.022 seconds
[2025-05-10T02:20:38.797+0000] {processor.py:186} INFO - Started process (PID=68656) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:20:38.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T02:20:38.806+0000] {logging_mixin.py:190} INFO - [2025-05-10T02:20:38.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:20:38.808+0000] {logging_mixin.py:190} INFO - [2025-05-10T02:20:38.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T02:20:38.809+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T02:20:38.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.031 seconds
[2025-05-10T03:21:36.005+0000] {processor.py:186} INFO - Started process (PID=68737) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T03:21:36.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T03:21:36.014+0000] {logging_mixin.py:190} INFO - [2025-05-10T03:21:36.013+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T03:21:36.019+0000] {logging_mixin.py:190} INFO - [2025-05-10T03:21:36.017+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T03:21:36.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T03:21:36.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.058 seconds
[2025-05-10T04:20:41.733+0000] {processor.py:186} INFO - Started process (PID=68818) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T04:20:41.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T04:20:41.736+0000] {logging_mixin.py:190} INFO - [2025-05-10T04:20:41.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T04:20:41.741+0000] {logging_mixin.py:190} INFO - [2025-05-10T04:20:41.738+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T04:20:41.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T04:20:41.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.029 seconds
[2025-05-10T04:57:31.582+0000] {processor.py:186} INFO - Started process (PID=68826) to work on /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T04:57:31.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_bash_python_with_xcom.py for tasks to queue
[2025-05-10T04:57:31.587+0000] {logging_mixin.py:190} INFO - [2025-05-10T04:57:31.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T04:57:31.618+0000] {logging_mixin.py:190} INFO - [2025-05-10T04:57:31.616+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_bash_python_with_xcom.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_python_with_xcom.py", line 10
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-05-10T04:57:31.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_python_with_xcom.py
[2025-05-10T04:57:31.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_bash_python_with_xcom.py took 0.102 seconds
