[2025-05-02T07:18:19.492+0000] {processor.py:186} INFO - Started process (PID=3416) to work on /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:18:19.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_python_import_func.py for tasks to queue
[2025-05-02T07:18:19.495+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:19.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:18:19.508+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:19.504+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_python_import_func.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/zoneinfo/_common.py", line 12, in load_tzdata
    return resources.files(package_name).joinpath(resource_name).open("rb")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/resources/_common.py", line 46, in wrapper
    return func(anchor)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/resources/_common.py", line 56, in files
    return from_package(resolve(anchor))
                        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 912, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/resources/_common.py", line 82, in _
    return importlib.import_module(cand)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata.zoneinfo.Asiz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/tz/timezone.py", line 65, in __new__
    return super().__new__(cls, key)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Asiz/Seoul'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_python_import_func.py", line 10, in <module>
    start_date=pendulum.datetime(2025, 3, 1, tz="Asiz/Seoul"),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/__init__.py", line 143, in datetime
    return DateTime.create(
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/datetime.py", line 103, in create
    tz = pendulum._safe_timezone(tz)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/__init__.py", line 124, in _safe_timezone
    return timezone(obj)
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/__init__.py", line 86, in timezone
    return Timezone(name)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/tz/timezone.py", line 67, in __new__
    raise InvalidTimezone(key)
pendulum.tz.exceptions.InvalidTimezone: Asiz/Seoul
[2025-05-02T07:18:19.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:18:19.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_python_import_func.py took 0.038 seconds
[2025-05-02T07:18:49.678+0000] {processor.py:186} INFO - Started process (PID=3485) to work on /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:18:49.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_python_import_func.py for tasks to queue
[2025-05-02T07:18:49.687+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:49.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:18:49.691+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:49.690+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags_python_import_func.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/zoneinfo/_common.py", line 12, in load_tzdata
    return resources.files(package_name).joinpath(resource_name).open("rb")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/resources/_common.py", line 46, in wrapper
    return func(anchor)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/resources/_common.py", line 56, in files
    return from_package(resolve(anchor))
                        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 912, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/resources/_common.py", line 82, in _
    return importlib.import_module(cand)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata.zoneinfo.Asiz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/tz/timezone.py", line 65, in __new__
    return super().__new__(cls, key)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Asiz/Seoul'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_python_import_func.py", line 10, in <module>
    start_date=pendulum.datetime(2025, 3, 1, tz="Asiz/Seoul"),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/__init__.py", line 143, in datetime
    return DateTime.create(
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/datetime.py", line 103, in create
    tz = pendulum._safe_timezone(tz)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/__init__.py", line 124, in _safe_timezone
    return timezone(obj)
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/__init__.py", line 86, in timezone
    return Timezone(name)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/tz/timezone.py", line 67, in __new__
    raise InvalidTimezone(key)
pendulum.tz.exceptions.InvalidTimezone: Asiz/Seoul
[2025-05-02T07:18:49.692+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:18:49.706+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_python_import_func.py took 0.032 seconds
[2025-05-02T07:18:53.702+0000] {processor.py:186} INFO - Started process (PID=3486) to work on /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:18:53.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_python_import_func.py for tasks to queue
[2025-05-02T07:18:53.705+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:53.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:18:53.712+0000] {processor.py:925} INFO - DAG(s) 'dags_python_import_func' retrieved from /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:18:53.790+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:53.789+0000] {override.py:1912} INFO - Created Permission View: can edit on DAG:dags_python_import_func
[2025-05-02T07:18:53.800+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:53.800+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG:dags_python_import_func
[2025-05-02T07:18:53.807+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:53.807+0000] {override.py:1912} INFO - Created Permission View: can read on DAG:dags_python_import_func
[2025-05-02T07:18:53.815+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:53.815+0000] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:dags_python_import_func
[2025-05-02T07:18:53.822+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:53.821+0000] {override.py:1912} INFO - Created Permission View: can create on DAG Run:dags_python_import_func
[2025-05-02T07:18:53.827+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:53.827+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:dags_python_import_func
[2025-05-02T07:18:53.833+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:53.833+0000] {override.py:1912} INFO - Created Permission View: can read on DAG Run:dags_python_import_func
[2025-05-02T07:18:53.834+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:53.834+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-02T07:18:53.844+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:53.843+0000] {dag.py:3262} INFO - Creating ORM DAG for dags_python_import_func
[2025-05-02T07:18:53.851+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:18:53.851+0000] {dag.py:4180} INFO - Setting next_dagrun for dags_python_import_func to 2025-04-30 21:30:00+00:00, run_after=2025-05-01 21:30:00+00:00
[2025-05-02T07:18:53.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_python_import_func.py took 0.166 seconds
[2025-05-02T07:19:24.087+0000] {processor.py:186} INFO - Started process (PID=3559) to work on /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:19:24.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_python_import_func.py for tasks to queue
[2025-05-02T07:19:24.091+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:19:24.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:19:24.098+0000] {processor.py:925} INFO - DAG(s) 'dags_python_import_func' retrieved from /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:19:24.113+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:19:24.113+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-02T07:19:24.132+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:19:24.131+0000] {dag.py:4180} INFO - Setting next_dagrun for dags_python_import_func to 2025-05-01 21:30:00+00:00, run_after=2025-05-02 21:30:00+00:00
[2025-05-02T07:19:24.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_python_import_func.py took 0.064 seconds
[2025-05-02T07:19:54.586+0000] {processor.py:186} INFO - Started process (PID=3628) to work on /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:19:54.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_python_import_func.py for tasks to queue
[2025-05-02T07:19:54.591+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:19:54.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:19:54.601+0000] {processor.py:925} INFO - DAG(s) 'dags_python_import_func' retrieved from /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:19:54.620+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:19:54.619+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-02T07:19:54.639+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:19:54.639+0000] {dag.py:4180} INFO - Setting next_dagrun for dags_python_import_func to 2025-05-01 21:30:00+00:00, run_after=2025-05-02 21:30:00+00:00
[2025-05-02T07:19:54.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_python_import_func.py took 0.074 seconds
[2025-05-02T07:20:25.575+0000] {processor.py:186} INFO - Started process (PID=3702) to work on /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:20:25.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags_python_import_func.py for tasks to queue
[2025-05-02T07:20:25.585+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:20:25.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:20:25.592+0000] {processor.py:925} INFO - DAG(s) 'dags_python_import_func' retrieved from /opt/airflow/dags/dags_python_import_func.py
[2025-05-02T07:20:25.609+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:20:25.609+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-02T07:20:25.627+0000] {logging_mixin.py:190} INFO - [2025-05-02T07:20:25.627+0000] {dag.py:4180} INFO - Setting next_dagrun for dags_python_import_func to 2025-05-01 21:30:00+00:00, run_after=2025-05-02 21:30:00+00:00
[2025-05-02T07:20:25.642+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags_python_import_func.py took 0.072 seconds
